name: rna-editing-pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - pandas
  - pyfaidx
  - bedtools
  - viennarna            # ViennaRNA + binding 
  - rnastructure         #  dot2ct ,draw
  - perl                 # /â€bpRNA
  - perl-graph           #  bpRNA 
